#!/bin/bash

# This script performs joint genotype calling
# on multiple raw genomic VCFs generated by GATK's HaplotypeCaller.
# It is passed a list of samples that actually map to S. cerevisiae.

# Load dependencies.
module load modules modules-init modules-gs
module load bcftools/1.3.1
module load java/8u25
module load GATK/3.7

# Input parameters.
samplelist="$1" # Give list of .g.vcf files to be combined in joint analysis.
reference="$2" # Give reference path WITHOUT .fasta or .fa extension.
dir="$3" # Give the desired location of intermediate output files.
sample="$4" # Give the short nickname for the output files.
clean="$5" # If 0, reruns entire pipeline and regenerates all intermediates.

# Notifies user when all intermediate files are being regenerated.
if [ ${clean} -eq "0" ]; then
  echo "Pipeline will run in its entirety, overwriting all existing intermediates."
fi

# Perform joint genotype calling on S. cerevisiae samples
# using GATK.
echo "Perform raw variant calling."
if [ ! -f ${dir}/${sample}-raw.vcf ] || [ $clean -eq "0" ];
then
  java -jar ${GATK_DIR}/GenomeAnalysisTK.jar \
    -T GenotypeGVCFs \
    -R ${reference}.fasta \
    -V ${samplelist} \
    -o ${dir}/${sample}-raw.vcf
fi

# Apply hard filters to the call set to produce a list of SNPs.
echo "Apply filters to raw variant calls."
if [ ! -f ${dir}/${sample}-snps-filtered.vcf ] || [ $clean -eq "0" ];
then
  # Extract SNPs from call set.
  java -jar ${GATK_DIR}/GenomeAnalysisTK.jar \
    -T SelectVariants \
    -R ${reference}.fasta \
    -V ${dir}/${sample}-raw.vcf \
    -selectType SNP \
    -o ${dir}/${sample}-snps-raw.vcf
	
  # Apply filters to call sets.
  java -jar ${GATK_DIR}/GenomeAnalysisTK.jar \
    -T VariantFiltration \
    -R ${reference}.fasta \
    -V ${dir}/${sample}-snps-raw.vcf \
    --filterExpression \
	  "QD < 2.0 || FS > 60.0 || MQ < 40.0 || MQRankSum < -12.5 || ReadPosRankSum < -8.0" \
    --filterName "GATK_Best_Practices_default" \
    -o ${dir}/${sample}-snps-tagged.vcf
	
  # Select only variants that have passed the filters.
  java -jar ${GATK_DIR}/GenomeAnalysisTK.jar \
    -T SelectVariants \
	-R ${reference}.fasta \
	-V ${dir}/${sample}-snps-tagged.vcf \
	-select 'vc.isNotFiltered()' \
	-o ${dir}/${sample}-snps-filtered.vcf
	
  # Remove intermediate files.
  rm -f ${dir}/${sample}-snps-raw.vcf
  rm -f ${dir}/${sample}-snps-tagged.vcf
fi

# Convert VCF to BCF files and generate statistics.
echo "Generate statistics."
if [ ! -f ${dir}/${sample}-snps-filtered.bcf ] || [ $clean -eq "0" ];
then
  # Convert the VCF to a BCF file.
  bcftools convert -Ou ${dir}/${sample}-snps-filtered.vcf \
    > ${dir}/${sample}-snps-filtered.bcf
	
  # Calculate statistics on the filtered variants.
  bcftools stats ${dir}/${sample}-snps-filtered.bcf \
    > ${dir}/${sample}-snps-filtered.stats
fi